version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - my-network

  rabbitmq-demo:
    build: .
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:

